plugins { id "com.android.application" }

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) localPropertiesFile.withInputStream { localProperties.load(it) }
def mobileAppKey = localProperties.getProperty("mobile.app.key", "")

android {
    namespace "com.yasamin.portfolioalerts"
    compileSdk 34

    defaultConfig {
        applicationId "com.yasamin.portfolioalerts"
        minSdk 26
        targetSdk 34
        versionCode 4
        versionName "1.3"
        buildConfigField "String", "MOBILE_APP_KEY", "\"${mobileAppKey}\""
    }

    buildFeatures { buildConfig true }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
    testOptions { unitTests.includeAndroidResources = true }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
    testImplementation "org.robolectric:robolectric:4.16.1"
}
