"use client";
import { useEffect,useMemo,useState } from "react";
import { defaultPortfolioConfig,portfolioConfigSchema,type PortfolioConfig } from "@/lib/portfolio-config";

type Tab="overview"|"profile"|"projects"|"artwork"|"motion"|"seo"|"inbox";
type Insights={messages:{id:number;name:string;email:string;message:string;locale:string;createdAt:number}[];analytics:{day:string;path:string;locale:string;views:number}[]};
const clone=()=>structuredClone(defaultPortfolioConfig);
const uid=()=>crypto.randomUUID().slice(0,8);

export function AdminDashboard(){
  const [content,setContent]=useState<PortfolioConfig>(clone); const [tab,setTab]=useState<Tab>("overview");
  const [status,setStatus]=useState("Loading your notebook…"); const [saving,setSaving]=useState(false); const [email,setEmail]=useState("");
  const [insights,setInsights]=useState<Insights|null>(null); const [insightsError,setInsightsError]=useState("");
  useEffect(()=>{Promise.all([fetch("/api/admin/session"),fetch("/api/admin/content")]).then(async([session,data])=>{
    if(!session.ok){window.location.replace("/login");return;}
    setEmail((await session.json()).email); const payload=await data.json(); const parsed=portfolioConfigSchema.safeParse(payload.content);
    if(parsed.success)setContent(parsed.data); setStatus(payload.updatedAt?`Last published ${new Date(payload.updatedAt*1000).toLocaleString()}`:"Ready to publish");
  }).catch(()=>setStatus("Could not reach the admin service"));},[]);
  useEffect(()=>{if(tab!=="inbox"||insights)return;fetch("/api/admin/insights").then(async response=>{if(!response.ok)throw new Error();setInsights(await response.json())}).catch(()=>setInsightsError("Could not load messages and visits."));},[tab,insights]);
  const score=useMemo(()=>{
    let value=45; if(content.settings.openToWork)value+=10; if(content.projects.filter(x=>x.visible).length>=3)value+=15;
    if(content.projects.some(x=>x.result.en.length>12))value+=10; if(content.profile.resumeUrl)value+=10; if(content.settings.linkedinUrl)value+=10; return Math.min(value,100);
  },[content]);
  async function save(){
    if(!portfolioConfigSchema.safeParse(content).success){setStatus("Some required fields are invalid.");return;}
    setSaving(true);setStatus("Publishing…");const results:(Response|null)[]=[];
    for(const section of Object.keys(content) as (keyof PortfolioConfig)[]){
      results.push(await fetch(`/api/admin/content?section=${section}`,{method:"DELETE"}).catch(()=>null));
      const value=content[section];let entries:{key:string;value:unknown}[];
      if(section==="projects")entries=content.projects.flatMap((item,index)=>{const group=`${String(index).padStart(3,"0")}-${item.id}`;return[{key:`${group}__core`,value:{id:item.id,name:item.name,imageUrl:item.imageUrl,repoUrl:item.repoUrl,liveUrl:item.liveUrl,tags:item.tags,featured:item.featured,visible:item.visible}},{key:`${group}__copy`,value:{summary:item.summary,description:item.description,status:item.status,role:item.role,result:item.result}}]});
      else entries=Array.isArray(value)?value.map((item,index)=>({key:`${String(index).padStart(3,"0")}-${item.id}`,value:item})):Object.entries(value).map(([key,item])=>({key,value:item}));
      for(let i=0;i<entries.length;i+=6){const group=await Promise.all(entries.slice(i,i+6).map(entry=>fetch("/api/admin/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({section,key:entry.key,value:entry.value})}).catch(()=>null)));results.push(...group);}
    }
    setSaving(false);setStatus(results.every(res=>res?.ok)?"Published — the public portfolio will refresh within about 30 seconds.":"Some entries could not publish. Please try again.");
  }
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.replace("/login");}
  const update=<K extends keyof PortfolioConfig>(key:K,value:PortfolioConfig[K])=>setContent(c=>({...c,[key]:value}));
  return <main className="admin-shell">
    <aside className="admin-sidebar"><div><span className="admin-kicker">YASAMIN / CONTROL ROOM</span><h1>Portfolio desk</h1><small>{email}</small></div>
      <nav>{(["overview","profile","projects","artwork","motion","seo","inbox"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
      <button className="admin-logout" onClick={logout}>Sign out</button>
    </aside>
    <section className="admin-workspace">
      <header className="admin-toolbar"><div><strong>{tab}</strong><span>{status}</span></div><button className="button button-dark" onClick={save} disabled={saving}>{saving?"Publishing…":"Publish changes"}</button></header>
      {tab==="overview"&&<section className="admin-panel"><h2>Hiring strength</h2><div className="hire-score"><strong>{score}</strong><span>/100</span><i style={{width:`${score}%`}} /></div><div className="admin-checks">
        <p className={content.settings.openToWork?"done":""}>State that you are open to work</p><p className={content.projects.length>=3?"done":""}>Show at least three substantial projects</p><p className={content.projects.some(x=>x.result.en)?"done":""}>Explain outcomes, not only tools</p><p className={content.profile.resumeUrl?"done":""}>Keep a downloadable résumé</p><p className={content.settings.linkedinUrl?"done":""}>Add LinkedIn for recruiter verification</p>
      </div><div className="admin-note"><h3>What improves hiring chances</h3><p>Lead each case study with your role, the problem, what you built and the result. Keep only your strongest work visible. Use the availability line for the exact roles you want.</p></div></section>}
      {tab==="profile"&&<section className="admin-panel"><h2>Profile and hiring message</h2><div className="admin-form-grid">
        <Bi label="Name" value={content.profile.name} onChange={v=>update("profile",{...content.profile,name:v})}/><Bi label="Role" value={content.profile.role} onChange={v=>update("profile",{...content.profile,role:v})}/><Bi label="Headline" value={content.profile.headline} onChange={v=>update("profile",{...content.profile,headline:v})}/><Bi label="Handwritten line" value={content.profile.headlineAccent} onChange={v=>update("profile",{...content.profile,headlineAccent:v})}/><Bi label="Introduction" area value={content.profile.intro} onChange={v=>update("profile",{...content.profile,intro:v})}/><Bi label="Availability" area value={content.profile.availability} onChange={v=>update("profile",{...content.profile,availability:v})}/>
        <Field label="Email" value={content.profile.email} onChange={v=>update("profile",{...content.profile,email:v})}/><Field label="Résumé URL" value={content.profile.resumeUrl} onChange={v=>update("profile",{...content.profile,resumeUrl:v})}/><Field label="Portrait URL" value={content.profile.portraitUrl} onChange={v=>update("profile",{...content.profile,portraitUrl:v})}/>
        <label className="admin-toggle"><input type="checkbox" checked={content.settings.openToWork} onChange={e=>update("settings",{...content.settings,openToWork:e.target.checked})}/><span>Show “open to work” signal</span></label>
      </div></section>}
      {tab==="projects"&&<Collection title="Development projects" addLabel="Add project" onAdd={()=>update("projects",[...content.projects,{id:uid(),name:"New project",imageUrl:"",repoUrl:"",liveUrl:"",summary:{en:"",fa:""},description:{en:"",fa:""},status:{en:"",fa:""},role:{en:"",fa:""},result:{en:"",fa:""},tags:[],featured:false,visible:false}])}>{content.projects.map((p,i)=><EditorCard key={p.id} title={p.name} visible={p.visible} onVisible={v=>{const a=[...content.projects];a[i]={...p,visible:v};update("projects",a)}} onDelete={()=>update("projects",content.projects.filter((_,n)=>n!==i))}>
        <Field label="Project name" value={p.name} onChange={v=>{const a=[...content.projects];a[i]={...p,name:v};update("projects",a)}}/><Field label="Preview image URL" value={p.imageUrl} onChange={v=>{const a=[...content.projects];a[i]={...p,imageUrl:v};update("projects",a)}}/><Field label="GitHub URL" value={p.repoUrl} onChange={v=>{const a=[...content.projects];a[i]={...p,repoUrl:v};update("projects",a)}}/><Field label="Live URL" value={p.liveUrl} onChange={v=>{const a=[...content.projects];a[i]={...p,liveUrl:v};update("projects",a)}}/><Bi label="Short summary" value={p.summary} onChange={v=>{const a=[...content.projects];a[i]={...p,summary:v};update("projects",a)}}/><Bi label="Case study" area value={p.description} onChange={v=>{const a=[...content.projects];a[i]={...p,description:v};update("projects",a)}}/><Bi label="Your role" value={p.role} onChange={v=>{const a=[...content.projects];a[i]={...p,role:v};update("projects",a)}}/><Bi label="Outcome / result" value={p.result} onChange={v=>{const a=[...content.projects];a[i]={...p,result:v};update("projects",a)}}/><Field label="Tags (comma separated)" value={p.tags.join(", ")} onChange={v=>{const a=[...content.projects];a[i]={...p,tags:v.split(",").map(x=>x.trim()).filter(Boolean)};update("projects",a)}}/>
      </EditorCard>)}</Collection>}
      {tab==="artwork"&&<Collection title="Illustration and design" addLabel="Add artwork" onAdd={()=>update("artworks",[...content.artworks,{id:uid(),imageUrl:"",title:{en:"New artwork",fa:"اثر جدید"},note:{en:"",fa:""},category:"Illustration",visible:false}])}>{content.artworks.map((a,i)=><EditorCard key={a.id} title={a.title.en} visible={a.visible} onVisible={v=>{const x=[...content.artworks];x[i]={...a,visible:v};update("artworks",x)}} onDelete={()=>update("artworks",content.artworks.filter((_,n)=>n!==i))}><Field label="Image URL" value={a.imageUrl} onChange={v=>{const x=[...content.artworks];x[i]={...a,imageUrl:v};update("artworks",x)}}/><Bi label="Title" value={a.title} onChange={v=>{const x=[...content.artworks];x[i]={...a,title:v};update("artworks",x)}}/><Bi label="Note" value={a.note} onChange={v=>{const x=[...content.artworks];x[i]={...a,note:v};update("artworks",x)}}/><Field label="Category" value={a.category} onChange={v=>{const x=[...content.artworks];x[i]={...a,category:v};update("artworks",x)}}/></EditorCard>)}</Collection>}
      {tab==="motion"&&<Collection title="Motion and video" addLabel="Add video" onAdd={()=>update("motion",[...content.motion,{id:uid(),videoUrl:"",posterUrl:"",title:{en:"New video",fa:"ویدئوی جدید"},note:{en:"",fa:""},portrait:false,visible:false}])}>{content.motion.map((m,i)=><EditorCard key={m.id} title={m.title.en} visible={m.visible} onVisible={v=>{const x=[...content.motion];x[i]={...m,visible:v};update("motion",x)}} onDelete={()=>update("motion",content.motion.filter((_,n)=>n!==i))}><Field label="Video URL" value={m.videoUrl} onChange={v=>{const x=[...content.motion];x[i]={...m,videoUrl:v};update("motion",x)}}/><Field label="Poster URL" value={m.posterUrl} onChange={v=>{const x=[...content.motion];x[i]={...m,posterUrl:v};update("motion",x)}}/><Bi label="Title" value={m.title} onChange={v=>{const x=[...content.motion];x[i]={...m,title:v};update("motion",x)}}/><Bi label="Note" value={m.note} onChange={v=>{const x=[...content.motion];x[i]={...m,note:v};update("motion",x)}}/><label className="admin-toggle"><input type="checkbox" checked={m.portrait} onChange={e=>{const x=[...content.motion];x[i]={...m,portrait:e.target.checked};update("motion",x)}}/>Portrait video</label></EditorCard>)}</Collection>}
      {tab==="seo"&&<section className="admin-panel"><h2>Links and discoverability</h2><div className="admin-form-grid"><Bi label="SEO title" value={content.settings.seoTitle} onChange={v=>update("settings",{...content.settings,seoTitle:v})}/><Bi label="SEO description" area value={content.settings.seoDescription} onChange={v=>update("settings",{...content.settings,seoDescription:v})}/><Field label="GitHub" value={content.settings.githubUrl} onChange={v=>update("settings",{...content.settings,githubUrl:v})}/><Field label="LinkedIn" value={content.settings.linkedinUrl} onChange={v=>update("settings",{...content.settings,linkedinUrl:v})}/><Field label="Instagram" value={content.settings.instagramUrl} onChange={v=>update("settings",{...content.settings,instagramUrl:v})}/></div></section>}
      {tab==="inbox"&&<section className="admin-panel"><h2>Inbox and visits</h2>{insightsError&&<p className="admin-empty">{insightsError}</p>}{!insights&&!insightsError&&<p className="admin-empty">Opening the notebook…</p>}{insights&&<><div className="admin-metrics"><article><strong>{insights.analytics.reduce((sum,row)=>sum+row.views,0)}</strong><span>consented page views</span></article><article><strong>{insights.messages.length}</strong><span>recent messages</span></article></div><h3 className="admin-subtitle">Messages</h3><div className="admin-message-list">{insights.messages.length?insights.messages.map(message=><article key={message.id}><header><strong>{message.name}</strong><a href={`mailto:${message.email}`}>{message.email}</a><time>{new Date(message.createdAt*1000).toLocaleString()}</time></header><p>{message.message}</p></article>):<p className="admin-empty">No messages yet.</p>}</div><h3 className="admin-subtitle">Recent page views</h3><div className="admin-visit-list">{insights.analytics.map((row,index)=><div key={`${row.day}-${row.path}-${row.locale}-${index}`}><time>{row.day}</time><code>{row.path}</code><span>{row.locale.toUpperCase()}</span><strong>{row.views}</strong></div>)}</div></>}</section>}
    </section>
  </main>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="admin-field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Bi({label,value,onChange,area=false}:{label:string;value:{en:string;fa:string};onChange:(v:{en:string;fa:string})=>void;area?:boolean}){const Tag=area?"textarea":"input";return <div className="admin-bi"><strong>{label}</strong><label><span>EN</span><Tag value={value.en} onChange={e=>onChange({...value,en:e.target.value})}/></label><label dir="rtl"><span>FA</span><Tag value={value.fa} onChange={e=>onChange({...value,fa:e.target.value})}/></label></div>}
function Collection({title,addLabel,onAdd,children}:{title:string;addLabel:string;onAdd:()=>void;children:React.ReactNode}){return <section className="admin-panel"><header className="admin-collection-head"><h2>{title}</h2><button onClick={onAdd}>＋ {addLabel}</button></header><div className="admin-collection">{children}</div></section>}
function EditorCard({title,visible,onVisible,onDelete,children}:{title:string;visible:boolean;onVisible:(v:boolean)=>void;onDelete:()=>void;children:React.ReactNode}){return <details className="admin-editor"><summary><strong>{title}</strong><span>{visible?"Visible":"Hidden"}</span></summary><div className="admin-editor-body"><div className="admin-editor-actions"><label className="admin-toggle"><input type="checkbox" checked={visible} onChange={e=>onVisible(e.target.checked)}/>Visible on portfolio</label><button onClick={onDelete}>Delete</button></div>{children}</div></details>}
