"use client";
import { useEffect,useMemo,useState } from "react";
import { defaultPortfolioConfig,portfolioConfigSchema,type PortfolioConfig } from "@/lib/portfolio-config";
import { PublicationManager } from "@/admin-components/PublicationManager";
import { PublicationOverview } from "@/admin-components/PublicationOverview";
import { AutomationPanel } from "@/admin-components/AutomationPanel";

type Tab="overview"|"articles"|"updates"|"automation"|"profile"|"projects"|"artwork"|"motion"|"seo"|"inbox";
type Insights={messages:{id:number;name:string;email:string;message:string;locale:string;createdAt:number}[];analytics:{day:string;path:string;locale:string;views:number}[];sessions:{sessionId:string;country:string;region:string;city:string;firstSeen:number;lastSeen:number;pageViews:number;eventCount:number}[];events:{sessionId:string;eventType:string;path:string;target:string;locale:string;createdAt:number}[];uniqueVisitors:number};
const clone=()=>structuredClone(defaultPortfolioConfig);
const uid=()=>crypto.randomUUID().slice(0,8);
const tabs:Tab[]=["overview","articles","updates","automation","profile","projects","artwork","motion","seo","inbox"];

export function AdminDashboard(){
  const [content,setContent]=useState<PortfolioConfig>(clone); const [tab,setTab]=useState<Tab>("overview");
  const [status,setStatus]=useState("Loading your notebook…"); const [saving,setSaving]=useState(false); const [email,setEmail]=useState("");
  const [insights,setInsights]=useState<Insights|null>(null); const [insightsError,setInsightsError]=useState("");
  useEffect(()=>{const timer=window.setTimeout(()=>{const saved=new URLSearchParams(window.location.search).get("tab")||sessionStorage.getItem("ys-admin-tab");if(saved&&tabs.includes(saved as Tab))setTab(saved as Tab)},0);return()=>window.clearTimeout(timer)},[]);
  useEffect(()=>{Promise.all([fetch("/api/admin/session"),fetch("/api/admin/content")]).then(async([session,data])=>{
    if(!session.ok){window.location.replace("/login");return;}
    setEmail((await session.json()).email); const payload=await data.json(); const parsed=portfolioConfigSchema.safeParse(payload.content);
    if(parsed.success)setContent(parsed.data); setStatus(payload.updatedAt?`Last published ${new Date(payload.updatedAt*1000).toLocaleString()}`:"Ready to publish");
  }).catch(()=>setStatus("Could not reach the admin service"));},[]);
  useEffect(()=>{if(tab!=="inbox")return;void refreshInsights();const timer=window.setInterval(()=>void refreshInsights(),10_000);return()=>window.clearInterval(timer)},[tab]);
  const score=useMemo(()=>{
    let value=45; if(content.settings.openToWork)value+=10; if(content.projects.filter(x=>x.visible).length>=3)value+=15;
    if(content.projects.some(x=>x.result.en.length>12))value+=10; if(content.profile.resumeUrl)value+=10; if(content.settings.linkedinUrl)value+=10; return Math.min(value,100);
  },[content]);
  async function save(){
    if(!portfolioConfigSchema.safeParse(content).success){setStatus("Some required fields are invalid.");return;}
    setSaving(true);setStatus("Publishing…");const results:(Response|null)[]=[];
    for(const section of Object.keys(content) as (keyof PortfolioConfig)[]){
      results.push(await fetch(`/api/admin/content?section=${section}`,{method:"DELETE"}).catch(()=>null));
      const value=content[section];let entries:{key:string;value:unknown}[];
      if(section==="projects")entries=content.projects.flatMap((item,index)=>{const group=`${String(index).padStart(3,"0")}-${item.id}`;return[{key:`${group}__core`,value:{id:item.id,name:item.name,imageUrl:item.imageUrl,desktopImageUrl:item.desktopImageUrl||"",mobileImageUrl:item.mobileImageUrl||"",repoUrl:item.repoUrl,liveUrl:item.liveUrl,assetUrl:item.assetUrl,tags:item.tags,featured:item.featured,visible:item.visible}},{key:`${group}__copy`,value:{summary:item.summary,description:item.description,status:item.status,role:item.role,result:item.result}}]});
      else entries=Array.isArray(value)?value.map((item,index)=>({key:`${String(index).padStart(3,"0")}-${item.id}`,value:item})):Object.entries(value).map(([key,item])=>({key,value:item}));
      for(let i=0;i<entries.length;i+=6){const group=await Promise.all(entries.slice(i,i+6).map(entry=>fetch("/api/admin/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({section,key:entry.key,value:entry.value})}).catch(()=>null)));results.push(...group);}
    }
    setSaving(false);setStatus(results.every(res=>res?.ok)?"Published — the public portfolio will refresh within about 30 seconds.":"Some entries could not publish. Please try again.");
  }
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.replace("/login");}
  async function refreshInsights(){try{const response=await fetch("/api/admin/insights",{cache:"no-store"});if(!response.ok)throw new Error();setInsights(await response.json());setInsightsError("")}catch{setInsightsError("Could not load messages and visits.")}}
  function chooseTab(next:Tab){setTab(next);sessionStorage.setItem("ys-admin-tab",next);const url=new URL(window.location.href);url.searchParams.set("tab",next);window.history.replaceState(null,"",url)}
  const update=<K extends keyof PortfolioConfig>(key:K,value:PortfolioConfig[K])=>setContent(c=>({...c,[key]:value}));
  return <main className="admin-shell">
    <aside className="admin-sidebar"><div><span className="admin-kicker">YASAMIN / CONTROL ROOM</span><h1>Portfolio desk</h1><small>{email}</small></div>
      <nav>{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>chooseTab(x)}>{x}</button>)}</nav>
      <button className="admin-logout" onClick={logout}>Sign out</button>
    </aside>
    <section className="admin-workspace">
      <header className="admin-toolbar"><div><strong>{tab}</strong><span>{status}</span></div>{!["articles","updates","automation","inbox"].includes(tab)&&<button className="button button-dark" onClick={save} disabled={saving}>{saving?"Publishing…":"Publish portfolio changes"}</button>}</header>
      {tab==="overview"&&<section className="admin-panel"><PublicationOverview/><h2>Hiring strength</h2><div className="hire-score"><strong>{score}</strong><span>/100</span><i style={{width:`${score}%`}} /></div><div className="admin-checks">
        <p className={content.settings.openToWork?"done":""}>State that you are open to work</p><p className={content.projects.length>=3?"done":""}>Show at least three substantial projects</p><p className={content.projects.some(x=>x.result.en)?"done":""}>Explain outcomes, not only tools</p><p className={content.profile.resumeUrl?"done":""}>Keep a downloadable résumé</p><p className={content.settings.linkedinUrl?"done":""}>Add LinkedIn for recruiter verification</p>
      </div><div className="admin-note"><h3>What improves hiring chances</h3><p>Lead each case study with your role, the problem, what you built and the result. Keep only your strongest work visible. Use the availability line for the exact roles you want.</p></div></section>}
      {tab==="articles"&&<PublicationManager type="article"/>}
      {tab==="updates"&&<PublicationManager type="signature-update"/>}
      {tab==="automation"&&<AutomationPanel/>}
      {tab==="profile"&&<section className="admin-panel"><h2>Profile and hiring message</h2><div className="admin-form-grid">
        <Bi label="Name" value={content.profile.name} onChange={v=>update("profile",{...content.profile,name:v})}/><Bi label="Role" value={content.profile.role} onChange={v=>update("profile",{...content.profile,role:v})}/><Bi label="Headline" value={content.profile.headline} onChange={v=>update("profile",{...content.profile,headline:v})}/><Bi label="Handwritten line" value={content.profile.headlineAccent} onChange={v=>update("profile",{...content.profile,headlineAccent:v})}/><Bi label="Introduction" area value={content.profile.intro} onChange={v=>update("profile",{...content.profile,intro:v})}/><Bi label="Availability" area value={content.profile.availability} onChange={v=>update("profile",{...content.profile,availability:v})}/>
        <Field label="Email" value={content.profile.email} onChange={v=>update("profile",{...content.profile,email:v})}/><UploadField label="Résumé" value={content.profile.resumeUrl} kind="file" accept=".pdf,.zip" onChange={v=>update("profile",{...content.profile,resumeUrl:v})}/><UploadField label="Portrait" value={content.profile.portraitUrl} kind="image" accept="image/*" onChange={v=>update("profile",{...content.profile,portraitUrl:v})}/>
        <label className="admin-toggle"><input type="checkbox" checked={content.settings.openToWork} onChange={e=>update("settings",{...content.settings,openToWork:e.target.checked})}/><span>Show “open to work” signal</span></label>
      </div></section>}
      {tab==="projects"&&<Collection title="Development projects" addLabel="Add project" onAdd={()=>update("projects",[...content.projects,{id:uid(),name:"New project",imageUrl:"",desktopImageUrl:"",mobileImageUrl:"",repoUrl:"",liveUrl:"",assetUrl:"",summary:{en:"",fa:""},description:{en:"",fa:""},status:{en:"",fa:""},role:{en:"",fa:""},result:{en:"",fa:""},tags:[],featured:false,visible:false}])}>{content.projects.map((p,i)=><EditorCard key={p.id} title={p.name} visible={p.visible} onVisible={v=>{const a=[...content.projects];a[i]={...p,visible:v};update("projects",a)}} onDelete={()=>update("projects",content.projects.filter((_,n)=>n!==i))}>
        <Field label="Project name" value={p.name} onChange={v=>{const a=[...content.projects];a[i]={...p,name:v};update("projects",a)}}/><UploadField label="Desktop mockup image" value={p.desktopImageUrl||p.imageUrl} kind="image" accept="image/*" onChange={v=>{const a=[...content.projects];a[i]={...p,imageUrl:v,desktopImageUrl:v};update("projects",a)}}/><UploadField label="Mobile mockup image (optional)" value={p.mobileImageUrl||""} kind="image" accept="image/*" onChange={v=>{const a=[...content.projects];a[i]={...p,mobileImageUrl:v};update("projects",a)}}/><Field label="GitHub URL (optional)" value={p.repoUrl} onChange={v=>{const a=[...content.projects];a[i]={...p,repoUrl:v};update("projects",a)}}/><Field label="Live URL (optional)" value={p.liveUrl} onChange={v=>{const a=[...content.projects];a[i]={...p,liveUrl:v};update("projects",a)}}/><UploadField label="Downloadable project file (optional)" value={p.assetUrl||""} kind="file" accept=".zip,.pdf" onChange={v=>{const a=[...content.projects];a[i]={...p,assetUrl:v};update("projects",a)}}/><Bi label="Short summary" value={p.summary} onChange={v=>{const a=[...content.projects];a[i]={...p,summary:v};update("projects",a)}}/><Bi label="Case study" area value={p.description} onChange={v=>{const a=[...content.projects];a[i]={...p,description:v};update("projects",a)}}/><Bi label="Your role" value={p.role} onChange={v=>{const a=[...content.projects];a[i]={...p,role:v};update("projects",a)}}/><Bi label="Outcome / result" value={p.result} onChange={v=>{const a=[...content.projects];a[i]={...p,result:v};update("projects",a)}}/><Field label="Tags (comma separated)" value={p.tags.join(", ")} onChange={v=>{const a=[...content.projects];a[i]={...p,tags:v.split(",").map(x=>x.trim()).filter(Boolean).slice(0,15)};update("projects",a)}}/>
      </EditorCard>)}</Collection>}
      {tab==="artwork"&&<Collection title="Illustration and design" addLabel="Add artwork" onAdd={()=>update("artworks",[...content.artworks,{id:uid(),imageUrl:"",title:{en:"New artwork",fa:"اثر جدید"},note:{en:"",fa:""},category:"Illustration",visible:false}])}>{content.artworks.map((a,i)=><EditorCard key={a.id} title={a.title.en} visible={a.visible} onVisible={v=>{const x=[...content.artworks];x[i]={...a,visible:v};update("artworks",x)}} onDelete={()=>update("artworks",content.artworks.filter((_,n)=>n!==i))}><UploadField label="Artwork image" value={a.imageUrl} kind="image" accept="image/*" onChange={v=>{const x=[...content.artworks];x[i]={...a,imageUrl:v};update("artworks",x)}}/><Bi label="Title" value={a.title} onChange={v=>{const x=[...content.artworks];x[i]={...a,title:v};update("artworks",x)}}/><Bi label="Note" value={a.note} onChange={v=>{const x=[...content.artworks];x[i]={...a,note:v};update("artworks",x)}}/><Field label="Category" value={a.category} onChange={v=>{const x=[...content.artworks];x[i]={...a,category:v};update("artworks",x)}}/></EditorCard>)}</Collection>}
      {tab==="motion"&&<Collection title="Motion and video" addLabel="Add video" onAdd={()=>update("motion",[...content.motion,{id:uid(),videoUrl:"",posterUrl:"",title:{en:"New video",fa:"ویدئوی جدید"},note:{en:"",fa:""},portrait:false,visible:false}])}>{content.motion.map((m,i)=><EditorCard key={m.id} title={m.title.en} visible={m.visible} onVisible={v=>{const x=[...content.motion];x[i]={...m,visible:v};update("motion",x)}} onDelete={()=>update("motion",content.motion.filter((_,n)=>n!==i))}><UploadField label="Video" value={m.videoUrl} kind="video" accept="video/mp4,video/webm" onChange={v=>{const x=[...content.motion];x[i]={...m,videoUrl:v};update("motion",x)}}/><UploadField label="Video poster" value={m.posterUrl} kind="image" accept="image/*" onChange={v=>{const x=[...content.motion];x[i]={...m,posterUrl:v};update("motion",x)}}/><Bi label="Title" value={m.title} onChange={v=>{const x=[...content.motion];x[i]={...m,title:v};update("motion",x)}}/><Bi label="Note" value={m.note} onChange={v=>{const x=[...content.motion];x[i]={...m,note:v};update("motion",x)}}/><label className="admin-toggle"><input type="checkbox" checked={m.portrait} onChange={e=>{const x=[...content.motion];x[i]={...m,portrait:e.target.checked};update("motion",x)}}/>Portrait video</label></EditorCard>)}</Collection>}
      {tab==="seo"&&<section className="admin-panel"><h2>Links and discoverability</h2><div className="admin-form-grid"><Bi label="SEO title" value={content.settings.seoTitle} onChange={v=>update("settings",{...content.settings,seoTitle:v})}/><Bi label="SEO description" area value={content.settings.seoDescription} onChange={v=>update("settings",{...content.settings,seoDescription:v})}/><Field label="GitHub" value={content.settings.githubUrl} onChange={v=>update("settings",{...content.settings,githubUrl:v})}/><Field label="LinkedIn" value={content.settings.linkedinUrl} onChange={v=>update("settings",{...content.settings,linkedinUrl:v})}/><Field label="Instagram" value={content.settings.instagramUrl} onChange={v=>update("settings",{...content.settings,instagramUrl:v})}/></div></section>}
      {tab==="inbox"&&<section className="admin-panel"><header className="admin-collection-head"><h2>Inbox and visitor activity</h2><button onClick={()=>void refreshInsights()}>↻ Refresh now</button></header>{insightsError&&<p className="admin-empty">{insightsError}</p>}{!insights&&!insightsError&&<p className="admin-empty">Opening the notebook…</p>}{insights&&<><div className="admin-metrics"><article><strong>{insights.uniqueVisitors}</strong><span>anonymous visitors</span></article><article><strong>{insights.sessions.length}</strong><span>recent sessions</span></article><article><strong>{insights.analytics.reduce((sum,row)=>sum+row.views,0)}</strong><span>page views</span></article><article><strong>{insights.messages.length}</strong><span>recent messages</span></article></div><p className="admin-privacy-note">Anonymous visits appear automatically and this page refreshes every 10 seconds. Network addresses are converted to non-reversible salted identifiers; the portfolio does not store raw IP addresses.</p><h3 className="admin-subtitle">Visitor sessions</h3><div className="admin-session-list">{insights.sessions.length?insights.sessions.map(session=><article key={session.sessionId}><header><strong>{[session.city,session.region,session.country].filter(Boolean).join(", ")||"Location unavailable"}</strong><time>{new Date(session.lastSeen*1000).toLocaleString()}</time></header><p>{session.pageViews} page views · {session.eventCount} recorded actions · session {session.sessionId.slice(0,8)}</p><div>{insights.events.filter(event=>event.sessionId===session.sessionId).slice(0,12).map((event,index)=><span key={`${event.createdAt}-${index}`}><b>{event.eventType.replaceAll("_"," ")}</b>{event.target?` · ${event.target}`:""} <small>{event.path}</small></span>)}</div></article>):<p className="admin-empty">No visitor sessions yet.</p>}</div><h3 className="admin-subtitle">Messages</h3><div className="admin-message-list">{insights.messages.length?insights.messages.map(message=><article key={message.id}><header><strong>{message.name}</strong><a href={`mailto:${message.email}`}>{message.email}</a><time>{new Date(message.createdAt*1000).toLocaleString()}</time></header><p>{message.message}</p></article>):<p className="admin-empty">No messages yet.</p>}</div><h3 className="admin-subtitle">Daily pages</h3><div className="admin-visit-list">{insights.analytics.map((row,index)=><div key={`${row.day}-${row.path}-${row.locale}-${index}`}><time>{row.day}</time><code>{row.path}</code><span>{row.locale.toUpperCase()}</span><strong>{row.views}</strong></div>)}</div></>}</section>}
    </section>
  </main>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="admin-field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>}
async function optimizeAdminImage(file:File){
  if(file.size<=1_450_000)return file;
  const bitmap=await createImageBitmap(file);let scale=Math.min(1,2000/Math.max(bitmap.width,bitmap.height));let blob:Blob|null=null;
  for(const quality of [.88,.8,.72,.64]){const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d")?.drawImage(bitmap,0,0,canvas.width,canvas.height);blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/webp",quality));if(blob&&blob.size<=1_450_000)break;scale*=.82;}
  bitmap.close();if(!blob||blob.size>1_500_000)throw new Error("This image could not be reduced below 1.5 MB. Please choose a smaller image.");
  return new File([blob],file.name.replace(/\.[^.]+$/,"")+".webp",{type:"image/webp"});
}
function UploadField({label,value,onChange,kind,accept}:{label:string;value:string;onChange:(v:string)=>void;kind:"image"|"video"|"file";accept:string}){const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");async function upload(file?:File){if(!file)return;setBusy(true);setMessage(`Preparing ${file.name}…`);try{const uploadFile=kind==="image"?await optimizeAdminImage(file):file;setMessage(`Uploading ${uploadFile.name}…`);const response=await fetch("/api/admin/media",{method:"POST",headers:{"Content-Type":uploadFile.type||"application/octet-stream","X-File-Name":uploadFile.name,"X-File-Size":String(uploadFile.size),"X-Media-Kind":kind},body:uploadFile});const result=await response.json();if(!response.ok)throw new Error(result.error||"Upload failed");onChange(result.url);setMessage("Uploaded — publish changes to show it on the portfolio.")}catch(error){setMessage(error instanceof Error?error.message:"Upload failed")}finally{setBusy(false)}}return <div className="admin-upload"><strong>{label}</strong>{kind==="image"&&value&&<img src={value} alt=""/>}<label className="admin-upload-button"><input type="file" accept={accept} disabled={busy} onChange={event=>void upload(event.target.files?.[0])}/><span>{busy?"Uploading…":value?"Replace upload":"Choose file to upload"}</span></label><label className="admin-field"><span>Or paste an existing URL</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>{message&&<small>{message}</small>}</div>}
function Bi({label,value,onChange,area=false}:{label:string;value:{en:string;fa:string};onChange:(v:{en:string;fa:string})=>void;area?:boolean}){const Tag=area?"textarea":"input";return <div className="admin-bi"><strong>{label}</strong><label><span>EN</span><Tag value={value.en} onChange={e=>onChange({...value,en:e.target.value})}/></label><label dir="rtl"><span>FA</span><Tag value={value.fa} onChange={e=>onChange({...value,fa:e.target.value})}/></label></div>}
function Collection({title,addLabel,onAdd,children}:{title:string;addLabel:string;onAdd:()=>void;children:React.ReactNode}){return <section className="admin-panel"><header className="admin-collection-head"><h2>{title}</h2><button onClick={onAdd}>＋ {addLabel}</button></header><div className="admin-collection">{children}</div></section>}
function EditorCard({title,visible,onVisible,onDelete,children}:{title:string;visible:boolean;onVisible:(v:boolean)=>void;onDelete:()=>void;children:React.ReactNode}){return <details className="admin-editor"><summary><strong>{title}</strong><span>{visible?"Visible":"Hidden"}</span></summary><div className="admin-editor-body"><div className="admin-editor-actions"><label className="admin-toggle"><input type="checkbox" checked={visible} onChange={e=>onVisible(e.target.checked)}/>Visible on portfolio</label><button onClick={onDelete}>Delete</button></div>{children}</div></details>}
