"use client";
import { useEffect,useMemo,useState } from "react";
import { defaultPublications } from "@/content-engine/default-content";
import { publicationSchema,type Publication,type PublicationType } from "@/content-engine/types";

const categories:Publication["category"][]=["AI","Frontend","Backend","Security","Tools","Industry","Career","Projects"];
 const blank=(type:PublicationType):Publication=>{const stamp=Math.floor(Date.now()/1000);return{id:crypto.randomUUID().slice(0,12),type,slug:"new-note",title:{en:"New note",fa:"یادداشت جدید"},shortDescription:{en:"",fa:""},answer:{en:"",fa:""},content:{en:"",fa:""},examples:{en:"",fa:""},expertOpinion:{en:"",fa:""},coverImage:"",category:type==="signature-update"?"Career":"Frontend",tags:[],publishDate:new Date().toISOString().slice(0,10),scheduledFor:"",featured:false,seoTitle:{en:"",fa:""},seoDescription:{en:"",fa:""},socialCaption:{en:"",fa:""},schemaData:{},author:"Yasamin Soraghi",readingTime:3,status:"draft",faq:[],sources:[],createdAt:stamp,updatedAt:stamp}};
export function PublicationManager({type}:{type:PublicationType}){
 const[items,setItems]=useState<Publication[]>([]),[selected,setSelected]=useState(""),[status,setStatus]=useState("Loading…"),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/admin/publications",{cache:"no-store"}).then(r=>r.json()).then(v=>{const stored=(v.items||[]) as Publication[];const deleted=new Set<string>(v.deletedDefaultIds||[]);const merged=new Map(defaultPublications.filter(x=>x.type===type&&!deleted.has(x.id)).map(x=>[x.id,x]));stored.filter(x=>x.type===type).forEach(x=>merged.set(x.id,x));const next=[...merged.values()];setItems(next);setSelected(next[0]?.id||"");setStatus(v.migrationRequired?"Database migration will be applied during deployment.":"Ready")}).catch(()=>setStatus("Could not load entries"))},[type]);
 const item=useMemo(()=>items.find(x=>x.id===selected),[items,selected]);
 const update=(patch:Partial<Publication>)=>setItems(current=>current.map(x=>x.id===selected?{...x,...patch}:x));
 async function save(nextStatus?:Publication["status"]){if(!item)return;const candidate={...item,status:nextStatus||item.status,updatedAt:Math.floor(Date.now()/1000)};const parsed=publicationSchema.safeParse(candidate);if(!parsed.success){setStatus(parsed.error.issues[0]?.message||"Invalid fields");return}setBusy(true);const response=await fetch("/api/admin/publications",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(candidate)});const result=await response.json();setBusy(false);if(response.ok){update({status:candidate.status,updatedAt:result.updatedAt});setStatus(candidate.status==="draft"?"Draft saved":"Published settings saved")}else setStatus(result.error||"Could not save")}
 async function remove(){if(!item)return;setBusy(true);const response=await fetch(`/api/admin/publications?id=${encodeURIComponent(item.id)}`,{method:"DELETE"});setBusy(false);if(response.ok){const next=items.filter(x=>x.id!==item.id);setItems(next);setSelected(next[0]?.id||"");setStatus("Deleted")}else setStatus("Could not delete")}
 function add(){const next=blank(type);setItems(current=>[next,...current]);setSelected(next.id);setStatus("New unsaved draft")}
 return <section className="admin-panel publication-manager"><header className="admin-collection-head"><div><h2>{type==="article"?"Articles":"Signature updates"}</h2><p>{status}</p></div><button onClick={add}>＋ New {type==="article"?"article":"update"}</button></header><div className="publication-workbench"><aside>{items.map(entry=><button key={entry.id} className={entry.id===selected?"active":""} onClick={()=>setSelected(entry.id)}><strong>{entry.title.en}</strong><span>{entry.status} · {entry.category}</span></button>)}</aside>{item?<div className="publication-editor"><div className="admin-editor-actions"><label className="admin-toggle"><input type="checkbox" checked={item.featured} onChange={e=>update({featured:e.target.checked})}/>Featured</label><select value={item.status} onChange={e=>update({status:e.target.value as Publication["status"]})}><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option></select><button onClick={remove} disabled={busy}>Delete</button></div>
 <div className="admin-form-grid"><Field label="Slug" value={item.slug} onChange={slug=>update({slug:slug.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")})}/><Field label="Author" value={item.author} onChange={author=>update({author})}/><label className="admin-field"><span>Category</span><select value={item.category} onChange={e=>update({category:e.target.value as Publication["category"]})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><Field label="Tags, comma separated" value={item.tags.join(", ")} onChange={value=>update({tags:value.split(",").map(x=>x.trim()).filter(Boolean).slice(0,15)})}/><Field label="Publish date" type="date" value={item.publishDate} onChange={publishDate=>update({publishDate})}/><Field label="Schedule time (optional)" type="datetime-local" value={item.scheduledFor} onChange={scheduledFor=>update({scheduledFor})}/><Field label="Reading time (minutes)" type="number" value={String(item.readingTime)} onChange={readingTime=>update({readingTime:Math.max(1,Number(readingTime)||1)})}/><UploadCover value={item.coverImage} onChange={coverImage=>update({coverImage})}/>
 <Bi label="Title" value={item.title} onChange={title=>update({title})}/><Bi label="Short description" area value={item.shortDescription} onChange={shortDescription=>update({shortDescription})}/><Bi label="Answer first" area value={item.answer} onChange={answer=>update({answer})}/><Bi label="Detailed explanation" area value={item.content} onChange={content=>update({content})}/><Bi label="Examples" area value={item.examples} onChange={examples=>update({examples})}/><Bi label="Developer perspective" area value={item.expertOpinion} onChange={expertOpinion=>update({expertOpinion})}/><Bi label="SEO title" value={item.seoTitle} onChange={seoTitle=>update({seoTitle})}/><Bi label="SEO description" area value={item.seoDescription} onChange={seoDescription=>update({seoDescription})}/><Bi label="Social caption" area value={item.socialCaption} onChange={socialCaption=>update({socialCaption})}/><TextList label="Sources — one title | URL per line" value={item.sources.map(x=>`${x.title} | ${x.url}`).join("\n")} onChange={value=>update({sources:value.split("\n").map(x=>x.split("|").map(y=>y.trim())).filter(x=>x[0]&&x[1]).map(([title,url])=>({title,url}))})}/><TextList label="FAQ — one EN question | EN answer | FA question | FA answer per line" value={item.faq.map(x=>`${x.question.en} | ${x.answer.en} | ${x.question.fa} | ${x.answer.fa}`).join("\n")} onChange={value=>update({faq:value.split("\n").map(x=>x.split("|").map(y=>y.trim())).filter(x=>x.length===4).map(([qen,aen,qfa,afa])=>({question:{en:qen,fa:qfa},answer:{en:aen,fa:afa}}))})}/><SchemaField value={item.schemaData} onChange={schemaData=>update({schemaData})}/></div>
 <div className="publication-actions"><button className="button button-outline" onClick={()=>void save("draft")} disabled={busy}>Save draft</button><button className="button button-dark" onClick={()=>void save(item.status==="scheduled"?"scheduled":"published")} disabled={busy}>{busy?"Saving…":item.status==="scheduled"?"Schedule":"Publish"}</button></div></div>:<p className="admin-empty">Create the first entry.</p>}</div></section>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="admin-field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Bi({label,value,onChange,area=false}:{label:string;value:{en:string;fa:string};onChange:(v:{en:string;fa:string})=>void;area?:boolean}){const Tag=area?"textarea":"input";return <div className="admin-bi publication-bi"><strong>{label}</strong><label><span>EN</span><Tag value={value.en} onChange={e=>onChange({...value,en:e.target.value})}/></label><label dir="rtl"><span>FA</span><Tag value={value.fa} onChange={e=>onChange({...value,fa:e.target.value})}/></label></div>}
function TextList({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="admin-field publication-list"><span>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)}/></label>}
function SchemaField({value,onChange}:{value:Record<string,unknown>;onChange:(v:Record<string,unknown>)=>void}){const[text,setText]=useState(JSON.stringify(value,null,2));const[error,setError]=useState("");return <label className="admin-field publication-list"><span>Additional schema data (advanced JSON)</span><textarea value={text} onChange={e=>{const next=e.target.value;setText(next);try{const parsed=JSON.parse(next);if(!parsed||Array.isArray(parsed)||typeof parsed!=="object")throw new Error();onChange(parsed);setError("")}catch{setError("Keep this as a valid JSON object")}}}/>{error&&<small>{error}</small>}</label>}
function UploadCover({value,onChange}:{value:string;onChange:(v:string)=>void}){const[busy,setBusy]=useState(false);async function upload(file?:File){if(!file)return;setBusy(true);const response=await fetch("/api/admin/media",{method:"POST",headers:{"Content-Type":file.type,"X-File-Name":file.name,"X-File-Size":String(file.size),"X-Media-Kind":"image"},body:file});const result=await response.json();if(response.ok)onChange(result.url);setBusy(false)}return <div className="admin-upload"><strong>Cover image</strong><label className="admin-upload-button"><input type="file" accept="image/*" disabled={busy} onChange={e=>void upload(e.target.files?.[0])}/><span>{busy?"Uploading…":"Upload cover"}</span></label><Field label="Or existing URL" value={value} onChange={onChange}/></div>}
